const dramas = [
    {
        id: 1,
        title: "死神与少年",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["小野塚小町", "圣白莲", "命莲", "八意永琳", "射命丸文", "琪露诺", "大妖精", "多多良小伞", "娜兹玲", "村纱水蜜", "云居一轮", "幽谷响子", "河城荷取", "水桥帕露西", "封兽鵺", "若鹭姬", "露米娅", "上白泽慧音", "星熊勇仪", "伊吹萃香", "铃仙", "博丽灵梦", "魂魄妖梦", "芙兰朵露", "四季映姬", "寅丸星"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBa1NoKDTH1nkAHgOwAHzhma",
        translatedUrl: "https://space.bilibili.com/12621850/lists/4882608",
        description: "你是我活过的证明。",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/1.jpg",
        dateAdded: "2023-06-18"
    },
    {
        id: 2,
        title: "幻想死洛谭",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["上白泽慧音", "琪露诺", "大妖精", "易者", "藤原妹红", "豫母都日狭美", "三头慧之子", "秦心", "比那名居天子", "永江衣玖", "犬走椛", "绵月依姬", "少名针妙丸", "稀神探女", "菅牧典", "铃仙", "芙兰朵露", "小野塚小町", "八意永琳", "丰聪耳神子", "八云蓝", "魂魄妖梦", "河城荷取", "星熊勇仪", "水桥帕露西", "射命丸文"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBZ63LCFxhe0uDIma4lgCMfC",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5066012",
        description: "死而未绝，络续不绝之缘。",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/2.jpg",
        dateAdded: "2024-08-24"
    },
    {
        id: 3,
        title: "幻想心狼殿",
        author: "ささきの茶釜",
        translator: "就是很一般",
        tags: ["古明地觉", "古明地恋", "魂魄妖梦", "芙兰朵露", "灵乌路空", "火焰猫燐", "藤原妹红"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBaXcAkHQes8-dkINhSlG-Aj",
        translatedUrl: "https://space.bilibili.com/12621850/lists/6561665",
        description: "一群变态似乎在拯救世界。",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/3.jpg",
        dateAdded: "2025-08-17"
    },
    {
        id: 4,
        title: "騒がしすぎて怖くない夜廻三",
        author: "ささきの茶釜",
        translator: "Baby_2016",
        tags: ["魂魄妖梦", "芙兰朵露", "十六夜咲夜", "洩矢诹访子", "博丽灵梦", "东风谷早苗", "雾雨魔理沙", "森近霖之助", "上白泽慧音", "蕾米莉亚", "爱丽丝"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLxioisTzjlBYrCViDpMBfFOEy1R4xNi1t",
        translatedUrl: "https://space.bilibili.com/499929312/lists/7392546",
        description: "夜明けまでに、呪いを解く方法を思い出せ。",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/4.jpg",
        dateAdded: "2022-08-10"
    },
    {
        id: 5,
        title: "吸血鬼と同棲⁉",
        author: "ねんねまるゆっくり",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "博丽灵梦", "芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL4PMLGSCaH8AF_vC-FcV9DTDU5XPCatxG",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6267690",
        description: "莫名其妙就要和吸血鬼同居了！？",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/5.jpg",
        dateAdded: "2020-05-29"
    },
    {
        id: 6,
        title: "红月夜的契约——与蕾米莉亚的彻夜醉迷",
        author: "不知火桃",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "古明地觉"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLFU-QWGTBq-4SsfGQuJBNzmvZtTzN3FoJ",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6324095",
        description: "学校的优等生竟和吸血鬼夜游！？",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/6.jpg",
        dateAdded: "2022-09-09"
    },
    {
        id: 7,
        title: "Bunny girl",
        author: "MISAKI 3518",
        translator: "寄遗忘之物于流年",
        tags: ["铃仙"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=ienoNid46dM&list=PLPIDlOi7aH3EiGs9HnU3Rg52r4j587qsI&index=6",
        translatedUrl: "https://www.bilibili.com/video/BV16A6QBCEqD/?vd_source=29215d7e01e2e3b79461f647961a787f",
        description: "与铃仙在酒吧的小故事",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/7.jpg",
        dateAdded: "2025-06-20"
    },
    {
        id: 8,
        title: "幻想怪異録",
        author: "ラングリィ",
        translator: "就是很一般",
        tags: ["十六夜咲夜", "蕾米莉亚", "芙兰朵露", "博丽灵梦", "雾雨魔理沙", "水桥帕露西", "藤原妹红"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLiZP5uzNOuqyLnTRnyb4ZT5LuoVlBxnyE",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5251532",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/8.jpg",
        dateAdded: "2021-03-24"
    },
    {
        id: 9,
        title: "东方海龟汤",
        author: "みつば【mituba】",
        translator: "就是很一般",
        tags: ["博丽灵梦", "雾雨魔理沙", "东风谷早苗", "十六夜咲夜", "魂魄妖梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLmc6eO_qCE4najTjdUCtXDa0Agx8tzDON",
        translatedUrl: "https://space.bilibili.com/12621850/lists/6172948",
        description: "大家听说过水平思考谜题吗？\n也被称为\"海龟汤\"呢。",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/9.jpg",
        dateAdded: "2021-04-04"
    },
    {
        id: 10,
        title: "欠了100亿的我被蕾米莉亚用100元买下了",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["蕾米莉亚", "芙兰朵露", "十六夜咲夜"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLeIWlGzrNsQUtLMAjpHAw4AN2U9j6-xwn",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5962069",
        description: "你听说过百元行的故事吗？",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/10.jpg",
        dateAdded: "2024-07-25"
    },
    {
        id: 11,
        title: "那些年我与小石头的恋爱攻防战",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["古明地恋"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPcclvKXISMZ2fy8POHkEd3sSA",
        translatedUrl: "https://www.bilibili.com/video/BV1ddhqztEJJ",
        description: "短篇故事，大概100集",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/11.jpg",
        dateAdded: "2024-07-31"
    },
    {
        id: 12,
        title: "创世神似乎在自己的世界挑战强者的样子",
        author: "DAIゆっくり",
        translator: "就是很一般",
        tags: ["八云紫", "蕾米莉亚", "芙兰朵露", "博丽灵梦", "古明地恋", "十六夜咲夜", "犬走椛", "雾雨魔理沙", "洩矢诹访子", "西行寺幽幽子", "魂魄妖梦", "上白泽慧音", "秦心"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2h240ZAgAYEaeVipLKlDJaK-FswRZMuu",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5697073",
        description: "非常有意思的战斗向茶剧",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/12.jpg",
        dateAdded: "2024-03-07"
    },
    {
        id: 13,
        title: "冷漠读心男幻想入",
        author: "白熱の親指",
        translator: "就是很一般",
        tags: ["博丽灵梦", "雾雨魔理沙", "露米娅", "东风谷早苗", "古明地恋", "八云紫", "幻想入"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=boGrjUJpBVo",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5116051",
        description: "一个在油管上比较有趣的幻想入系列，但有着原创主人公、角色暴力表现。觉得不OK的慎入",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/13.jpg",
        dateAdded: "2024-12-06"
    },
    {
        id: 14,
        title: "河童世界谚语剧场",
        author: "須方のさんちゃん工房",
        translator: "就是很一般",
        tags: ["纯狐", "八云蓝", "小恶魔", "雾雨魔理沙", "神绮", "摩多罗隐岐奈", "宫出口瑞灵", "维缦浅间", "河城荷取", "依神女苑", "八云紫", "易者", "朱鹭子", "渡里妮娜", "洩矢诹访子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=tL5lu9jG9m8",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5104404",
        description: "世界谚语科普",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/14.jpg",
        dateAdded: "2022-08-13"
    },
    {
        id: 15,
        title: "天才的我被IQ9的后辈琪露诺告白了",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["琪露诺", "大妖精", "露米娅"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=6cME-im2kDE",
        translatedUrl: "https://space.bilibili.com/12621850/lists/7228361",
        description: "这是啥子角色？",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/15.jpg",
        dateAdded: "2021-12-27"
    },
    {
        id: 16,
        title: "爱上可爱妖梦.....但是",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["魂魄妖梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPccn24qH-xfKfS2XQTJY30Fuu",
        translatedUrl: "https://space.bilibili.com/12621850/lists/6626365",
        description: "魂魄妖梦，你毁了我的性取向",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/16.jpg",
        dateAdded: "2019-02-16"
    },
    {
        id: 17,
        title: "东方永梦樱",
        author: "みつば【mituba】",
        translator: "Baby_2016",
        tags: ["西行寺幽幽子", "八云紫", "魂魄妖梦", "博丽灵梦", "十六夜咲夜", "雾雨魔理沙", "东风谷早苗", "蕾米莉亚", "芙兰朵露", "宫古芳香", "铃仙", "绵月依姬", "藤原妹红", "八云蓝", "上白泽慧音", "古明地恋", "幻想入"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLmc6eO_qCE4nYR7tYmTsppAF1CTxhcrTP",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6449310",
        description: "佛前樱散祈缘契，愿渡来生共世人。",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/17.jpg",
        dateAdded: "2018-10-14"
    },
    {
        id: 18,
        title: "自杀未遂后竟然和蕾米莉亚开始交往了!?",
        author: "幻夢 ゆっくり茶番劇",
        translator: "Baby_2016",
        tags: ["蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLwnprYHAfPHaqEZqQFi2nQiPLg5Igo3mT",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6466841",
        description: "无刀可放心食用",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/18.jpg",
        dateAdded: "2025-07-24"
    },
    {
        id: 19,
        title: "幻想入沃尔加",
        author: "ゆっくりヴォルガ",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "芙兰朵露", "十六夜咲夜", "易者", "帕秋莉", "辉夜", "藤原妹红", "古明地恋", "古明地觉", "铃仙", "魂魄妖梦", "茨木华扇", "姬海棠果", "射命丸文", "犬走椛", "洩矢诹访子", "八坂神奈子", "东风谷早苗", "二岩猯藏", "红美铃", "小恶魔", "幻想入"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLn5zMpk5-YR-Qzz5RcosD3oA5MbuMk23V",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6525221",
        description: "mmd和茶番剧二合一",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/19.jpg",
        dateAdded: "2024-07-31"
    },
    {
        id: 20,
        title: "谈了一场如魔法般的恋爱",
        author: "幻夢 ゆっくり茶番劇",
        translator: "Baby_2016",
        tags: ["帕秋莉"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLwnprYHAfPHZ0bKlsSRE1CQYkWNYw5L6U",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6702992",
        description: "帕秋莉厨必看系列",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/20.jpg",
        dateAdded: "2025-09-12"
    },
    {
        id: 21,
        title: "拯救被欺凌男孩的天使妹妹",
        author: "シク−Siku−   ゆっくり",
        translator: "Baby_2016",
        tags: ["蕾米莉亚", "芙兰朵露", "十六夜咲夜", "洩矢诹访子", "吉吊八千慧", "博丽灵梦", "八坂神奈子", "幻想入"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLkONYltbNkGdPwu1CVug0NyOROBUShYqh",
        translatedUrl: "https://space.bilibili.com/499929312/lists/6809460",
        description: "繧?▲縺上ｊ縺励※縺?▲縺ｦ縺ｭ?",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/21.jpg",
        dateAdded: "2023-10-01"
    },
    {
        id: 22,
        title: "染上色彩的恋爱始于你",
        author: "ゆっくり春",
        translator: "Baby_2016",
        tags: ["圣白莲", "命莲", "八云紫", "博丽灵梦", "露米娅", "稗田阿求", "本居小铃", "上白泽慧音", "寅丸星", "幽谷响子", "云居一轮", "村纱水蜜", "森近霖之助", "爱丽丝", "宇佐见莲子", "小恶魔", "帕秋莉", "封兽鵺", "多多良小伞", "风见幽香", "蕾米莉亚", "芙兰朵露", "藤原妹红", "铃仙", "琪露诺", "红美铃", "大妖精", "米斯蒂娅", "莉格露", "魂魄妖梦", "西行寺幽幽子", "幻想入"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLwsFUfY3oQWJ3GsyshggcsJbI6_X8hRD0",
        translatedUrl: "https://space.bilibili.com/499929312/lists/7221002",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/22.jpg",
        dateAdded: "2024-08-23"
    },
    {
        id: 23,
        title: "这里是幻想高中话剧部！",
        author: "OKOME",
        translator: "一脚踢飞毛布",
        tags: ["秋静叶", "博丽灵梦", "鬼人正邪", "上白泽慧音", "八云紫", "魂魄妖忌", "魂魄妖梦", "雾雨魔理沙", "西行寺幽幽子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL-pkvuGg-eTBtbPiC-dhheSrl0GaAeifd",
        translatedUrl: "https://space.bilibili.com/33819012/lists/6789016",
        description: "来演话剧吧！博丽同学！",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/23.jpg",
        dateAdded: "2025-02-10"
    },
    {
        id: 24,
        title: "博丽灵梦消失的那一天",
        author: "みつば【mituba】",
        translator: "幻想入的Jier",
        tags: ["博丽灵梦", "雾雨魔理沙", "东风谷早苗", "蕾米莉亚", "西行寺幽幽子", "八意永琳", "铃仙"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=y6Kwj56KTCE",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4535137",
        description: "如果你最珍视的人明天就要离世了，你会怎么做？",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/24.jpg",
        dateAdded: "2021-06-07"
    },
    {
        id: 25,
        title: "满脑子黄色废料的心酱",
        author: "不知火桃",
        translator: "幻想入的Jier",
        tags: ["秦心", "丰聪耳神子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=7_eM4AAt3XM",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4845021",
        description: "我这人啊，就是爱瞎操心",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/25.jpg",
        dateAdded: "2022-10-09"
    },
    {
        id: 26,
        title: "○○空间",
        author: "KOTATU",
        translator: "幻想入的Jier",
        tags: ["博丽灵梦", "雾雨魔理沙", "蕾米莉亚", "芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=SoOBZO_n5gU",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5078005",
        description: "想要出去就只能○○的房间",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/26.jpg",
        dateAdded: "2023-11-07"
    },
    {
        id: 27,
        title: "【みるもるの家】作者的茶番剧合集",
        author: "みるもるの家",
        translator: "幻想入的Jier",
        tags: ["古明地恋", "古明地觉", "蕾米莉亚", "芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=t-vZgFACfmw",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4780455",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/27.jpg",
        dateAdded: "2021-11-14"
    },
    {
        id: 28,
        title: "Super_Nakachan作者的贴贴合集",
        author: "Super_Nakachan",
        translator: "幻想入的Jier",
        tags: ["博丽灵梦", "雾雨魔理沙", "射命丸文", "蕾米莉亚", "帕秋莉", "爱丽丝", "八云紫", "古明地觉", "古明地恋", "八云紫", "摩多罗隐岐奈", "十六夜咲夜"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=NNAi4rWxy4k",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4396885",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/28.jpg",
        dateAdded: "2022-08-05"
    },
    {
        id: 29,
        title: "病娇芙兰对我展开了猛烈追求！？",
        author: "転生さん",
        translator: "幻想入的Jier",
        tags: ["芙兰朵露", "宇佐见莲子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLl_rWSOGGXM8ULORk8_P5JQJEc4AIEz4W",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4409450",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/29.jpg",
        dateAdded: "2020-09-02"
    },
    {
        id: 30,
        title: "【月田瑞希】的桃子文茶番剧合集",
        author: "月田瑞希",
        translator: "幻想入的Jier",
        tags: ["芙兰朵露", "古明地恋", "古明地觉", "博丽灵梦", "多多良小伞", "秦心", "琪露诺", "上白泽慧音", "蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=qrRNO2w6JqE",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5117741",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/30.jpg",
        dateAdded: "2025-02-03"
    },
    {
        id: 31,
        title: "【東方キャラと恋愛するノベル動画ch】的茶番剧合集",
        author: "東方キャラと恋愛するノベル動画ch",
        translator: "幻想入的Jier",
        tags: ["十六夜咲夜", "古明地觉", "魂魄妖梦", "琪露诺", "蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=U_hPtTKAMlM",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5574603",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/31.jpg",
        dateAdded: "2022-10-02"
    },
    {
        id: 32,
        title: "始于小伞的恋物语",
        author: "みとは ゆっくり製作所",
        translator: "幻想入的Jier",
        tags: ["多多良小伞", "封兽鵺", "博丽灵梦", "雾雨魔理沙", "东风谷早苗", "十六夜咲夜"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLVBIKA03FhZPjrYJAJ4Qb3bXCZAyE8jyv",
        translatedUrl: "https://space.bilibili.com/87123918/lists/4758726",
        description: "雨爱的秘密，会一直延续~",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/32.jpg",
        dateAdded: "2023-01-13"
    },
    {
        id: 33,
        title: "彼夏拾遗",
        author: "〆タケ",
        translator: "幻想入的Jier",
        tags: ["蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=c6mxNbdWinY",
        translatedUrl: "https://www.bilibili.com/video/BV1Uqo8YEEGr",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/33.jpg",
        dateAdded: "2024-08-18"
    },
    {
        id: 34,
        title: "忠犬灵梦爱上我？！",
        author: "ゆっくり紫月",
        translator: "幻想入的Jier,山上的幽灵_",
        tags: ["依莉斯", "博丽灵梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=6KldaHy1u0I",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5409881",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/34.jpg",
        dateAdded: "2025-03-03"
    },
    {
        id: 35,
        title: "古今西行歌枕",
        author: "森の民やむぅ",
        translator: "幻想入的Jier,Baby_2016,TheUsualHeartFade123, 降り注ぐ星の光",
        tags: ["西行寺幽幽子", "八云紫", "魂魄妖梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.nicovideo.jp/watch/sm28681278",
        translatedUrl: "https://space.bilibili.com/87123918/lists/5224003",
        description: "莫问来生伴谁侧，樱花落处即相逢。",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/35.jpg",
        dateAdded: "2016-04-23"
    },
    {
        id: 36,
        title: "xxx变成病娇了……？",
        author: "れくしぃちきん@ゆっくり茶番劇",
        translator: "幻想入的Jier",
        tags: ["博丽灵梦", "雾雨魔理沙", "芙兰朵露", "幻想入"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL3rAsEOjJPkNOjHdzZr77LpCrL1C69gKP",
        translatedUrl: "https://space.bilibili.com/87123918/lists/6936080",
        description: "想起了…",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/36.jpg",
        dateAdded: "2020-10-01"
    },
    {
        id: 37,
        title: "青梅竹马的恋恋想让我心动",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["古明地恋"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOuyorGr52XSbjp9DQbJQ3mBS",
        translatedUrl: "https://www.bilibili.com/video/BV1mxdSYeE62",
        description: "恋恋可爱捏（",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/37.jpg",
        dateAdded: "2020-05-14"
    },
    {
        id: 38,
        title: "进来让蕾咪强控你26秒",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/shorts/S7oAsAhm0NU",
        translatedUrl: "https://www.bilibili.com/video/BV1jDdbYoEca",
        description: "蕾米可爱捏",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/38.jpg",
        dateAdded: "2024-03-10"
    },
    {
        id: 39,
        title: "无法吃人的食人妖怪",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["露米娅", "博丽灵梦", "雾雨魔理沙", "古明地恋", "卡娜安娜贝拉尔"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOux8cq6dLe9S47gQJkk_uuZz",
        translatedUrl: "https://www.bilibili.com/video/BV1emAseZEwa",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/39.jpg",
        dateAdded: "2020-06-14"
    },
    {
        id: 40,
        title: "渺小之人的伟大勇气",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["琪露诺", "大妖精", "米斯蒂娅", "莉格露", "露米娅", "上白泽慧音"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOuzcuFHQqi6LQQpGDJUGiTPz",
        translatedUrl: "https://www.bilibili.com/video/BV1wFRVYXE9m",
        description: "以baka小队为主角的系列~",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/40.jpg",
        dateAdded: "2024-03-02"
    },
    {
        id: 41,
        title: "平凡的我与、天才般的你",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["蕾米莉亚", "东风谷早苗", "芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOuxc9DJkmjOcEkTYfUehOCXb",
        translatedUrl: "https://www.bilibili.com/video/BV1mtPveLEjJ",
        description: "在无数重复的时间线中，我的声音定能再度围绕你左右。",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/41.jpg",
        dateAdded: "2024-08-30"
    },
    {
        id: 42,
        title: "世界上最难操作的游戏",
        author: "アスター",
        translator: "幻想入的Jier",
        tags: ["雾雨魔理沙", "蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL5Ezg2qezOuwb0u1PD_ipY9UREG6ig5fJ",
        translatedUrl: "https://www.bilibili.com/video/BV1ZEdZY3ERs",
        description: "可以看到蕾米花式破防的一集（",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/42.jpg",
        dateAdded: "2024-09-21"
    },
    {
        id: 43,
        title: "即使如此，帕露西依然选择当个家里蹲",
        author: "ラカルとゆっくりB",
        translator: "寄遗忘之物于流年",
        tags: ["水桥帕露西", "茨木华扇"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=LqAzlj1yJGA",
        translatedUrl: "https://space.bilibili.com/109338384/lists/6835169",
        description: "留学回来之后，青梅竹马的帕露西居然退学了，还当了家里蹲？！",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/43.jpg",
        dateAdded: "2020-05-14"
    },
    {
        id: 44,
        title: "蛙之季",
        author: "ラカルとゆっくりB",
        translator: "寄遗忘之物于流年",
        tags: ["洩矢诹访子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=6H-RJpUbXbE",
        translatedUrl: "https://space.bilibili.com/109338384/lists/6859688",
        description: "。我重生了，回到了我初中一年级入学的时候，这次，我要改变我的命运，不再成为一个40岁一事无成碌碌无为的社畜",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/44.jpg",
        dateAdded: "2019-03-15"
    },
    {
        id: 45,
        title: "女难之相的我与表姐与女性朋友",
        author: "あーる。/ aru",
        translator: "寄遗忘之物于流年",
        tags: ["绵月依姬", "绵月丰姬", "冴月麟"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLkbhAsj-moQyC4JME0vR2_OrKR2r8GNFt",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7099795",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/45.jpg",
        dateAdded: "2021-06-18"
    },
    {
        id: 46,
        title: "与奴隶少女觉的同居生活",
        author: "ルナ「露優」",
        translator: "寄遗忘之物于流年",
        tags: ["古明地觉", "菅牧典"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLsU0BZFJZhxU18cReRmpsGDqJD8AwDL9D",
        translatedUrl: "https://space.bilibili.com/109338384/lists/6834497",
        description: "与可爱的奴隶少女觉开启了同居生活……",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/46.jpg",
        dateAdded: "2022-07-01"
    },
    {
        id: 47,
        title: "身患恐女症的我，竟多了个义妹！？",
        author: "じぇすさんのゆっくり部屋",
        translator: "寄遗忘之物于流年",
        tags: ["多多良小伞", "物部布都", "上白泽慧音"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL3YhIU0YsQWPDaRyBdd1Owi4Fidnj6n3L",
        translatedUrl: "https://space.bilibili.com/109338384/lists/6829056",
        description: "为了防止新的义妹进入到我家，我对自己的家进行了要塞计划，可惜被老爹直接叫停，然而当我一打开门，遇到的却是……",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/47.jpg",
        dateAdded: "2023-05-15"
    },
    {
        id: 48,
        title: "夏露露",
        author: "まったりさん",
        translator: "寄遗忘之物于流年",
        tags: ["蕾米莉亚", "多多良小伞"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPcclXhofki7-qmExJa24NPwia",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7238326",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/48.jpg",
        dateAdded: "2018-05-30"
    },
    {
        id: 49,
        title: "孤独的幻想入",
        author: "MISAKI 3518",
        translator: "寄遗忘之物于流年",
        tags: ["雾雨魔理沙", "博丽灵梦", "射命丸文", "十六夜咲夜", "冴月麟", "东风谷早苗", "铃仙", "河城荷取", "爱丽丝", "幻想入"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLPIDlOi7aH3Fk5iGBIjN_iBSQFUWHOrsd",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7150145",
        description: "幻想乡……真是厉害啊",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/49.jpg",
        dateAdded: "2021-10-19"
    },
    {
        id: 50,
        title: "由于父母再婚，我与关系水火不容的妹红成为了家人",
        author: "かめーーとあらら",
        translator: "寄遗忘之物于流年",
        tags: ["藤原妹红"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=oooMSfHdcbY",
        translatedUrl: "https://www.bilibili.com/video/BV1b3U7BUEpY",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/50.jpg",
        dateAdded: "2023-11-04"
    },
    {
        id: 51,
        title: "学园里最令人畏惧的不良少女妹红，实际上似乎是个弟控呢",
        author: "ゆっくり「モナカ」",
        translator: "寄遗忘之物于流年",
        tags: ["藤原妹红", "铃仙"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLIbahIQ3NnZtSsbNwlFXr5a3RsEgfuwhX",
        translatedUrl: "https://www.bilibili.com/video/BV1J6i3BHEV6",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/51.jpg",
        dateAdded: "2023-12-10"
    },
    {
        id: 52,
        title: "【東方紙芝居物語】老师的病娇系列",
        author: "東方紙芝居物語",
        translator: "我都没眼看123",
        tags: ["病娇", "蕾米莉亚", "博丽灵梦", "射命丸文", "雾雨魔理沙", "十六夜咲夜", "风见幽香", "藤原妹红", "芙兰朵露", "魂魄妖梦", "灵乌路空", "绵月依姬", "犬走椛", "村纱水蜜", "鬼人正邪", "丰聪耳神子", "寅丸星", "圣白莲", "云居一轮", "封兽鵺"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/@TouhouYandere8901",
        translatedUrl: "https://space.bilibili.com/2065248047/lists/1619296",
        description: "入坑东方必看作",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/52.jpg",
        dateAdded: "2021-08-17"
    },
    {
        id: 53,
        title: "映姬的恐怖审判",
        author: "はやぶさ_ゆっくり茶番劇",
        translator: "我都没眼看123",
        tags: ["四季映姬"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLMqWBRhqHwItIaeEd64Ym8kld9AxB--Q5",
        translatedUrl: "https://space.bilibili.com/2065248047/lists/1885948",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/53.jpg",
        dateAdded: "2021-11-02"
    },
    {
        id: 54,
        title: "某个女孩和我",
        author: "きまぐれい『漫画部』",
        translator: "兴趣使然的鸽子口牙",
        tags: ["多多良小伞", "秦心", "琪露诺"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLwVn04n1IKXuNrDa7luvafJtZqJLrS6VP",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6831118",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/54.jpg",
        dateAdded: "2023-04-18"
    },
    {
        id: 55,
        title: "我遇到了一个能读心的女孩？！",
        author: "いなよりこりん",
        translator: "兴趣使然的鸽子口牙",
        tags: ["古明地觉"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL0y_WAo04qpoPSPJzyG5e00ZDK7zDROfT",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6831140",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/55.jpg",
        dateAdded: "2020-06-24"
    },
    {
        id: 56,
        title: "给朋友钱让他穿女装太可爱了",
        author: "アルカイ教",
        translator: "兴趣使然的鸽子口牙",
        tags: ["依神紫苑", "古明地恋", "爱丽丝"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLueexuf60TEYtkvqS3kpCtfUwY31zpDmu",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6831143",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/56.jpg",
        dateAdded: "2022-07-10"
    },
    {
        id: 57,
        title: "被女孩包围",
        author: "すみかぜハヤテ",
        translator: "兴趣使然的鸽子口牙",
        tags: ["博丽灵梦", "雾雨魔理沙", "蕾米莉亚", "古明地恋", "东风谷早苗", "秦心", "芙兰朵露", "水桥帕露西", "魂魄妖梦", "西行寺幽幽子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLpSzC1-Y_uEF1Ru4IDjPXeXD_N-ZuHwO8",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6837350",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/57.jpg",
        dateAdded: "2020-12-29"
    },
    {
        id: 58,
        title: "消失的天才少女",
        author: "るちょ",
        translator: "兴趣使然的鸽子口牙",
        tags: ["爱丽丝"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLDnwQpBnibfJtE-9aDJK6gW4IyH9GeAJi",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6847416?type=season",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/58.jpg",
        dateAdded: "2025-08-24"
    },
    {
        id: 59,
        title: "不善言辞的青梅竹马“觉”竟然是租借女友",
        author: "ゆっくりコスモス",
        translator: "兴趣使然的鸽子口牙",
        tags: ["古明地觉", "古明地恋", "爱丽丝", "射命丸文"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLAhdzhAf7V75BY4JESOW4ApKBdL3xhObR",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6866081",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/59.jpg",
        dateAdded: "2024-09-14"
    },
    {
        id: 60,
        title: "我妻子雷米莉亚是傲娇",
        author: "えーり",
        translator: "兴趣使然的鸽子口牙",
        tags: ["蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_7ejg7TDX983ZPYfpT7oDNf",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6884763",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/60.jpg",
        dateAdded: "2024-12-18"
    },
    {
        id: 61,
        title: "小石变成猫了",
        author: "いなよりこりん",
        translator: "兴趣使然的鸽子口牙",
        tags: ["古明地恋"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPcckBBa2XYhkNyAgF4UXgWVUQ",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6886121",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/61.jpg",
        dateAdded: "2019-08-07"
    },
    {
        id: 62,
        title: "被病娇的蕾米莉亚缠上了！？",
        author: "えーり",
        translator: "兴趣使然的鸽子口牙",
        tags: ["蕾米莉亚", "病娇"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_5mB4A0gda1yms9PZatnShM",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6894045?type=season",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/62.jpg",
        dateAdded: "2024-06-14"
    },
    {
        id: 63,
        title: "试图自杀的少女是盲人",
        author: "らうさん",
        translator: "兴趣使然的鸽子口牙",
        tags: ["古明地觉", "八意永琳"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLEitLOfPT9XvigVfXwqKqT4avo7BmjJ_8",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6904781",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/63.jpg",
        dateAdded: "2023-08-22"
    },
    {
        id: 64,
        title: "班里的小伞这么狡猾，似乎都是我的错",
        author: "えーり",
        translator: "兴趣使然的鸽子口牙",
        tags: ["多多良小伞"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_6RiAuIEo_IbTHSMGAhkhKS",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/6910538",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/64.jpg",
        dateAdded: "2025-06-11"
    },
    {
        id: 65,
        title: "超级纯洁的爱丽丝宠我！？",
        author: "えーり",
        translator: "兴趣使然的鸽子口牙",
        tags: ["爱丽丝"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_43iJW3K6PYwomcyjuCJI0N",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/7229554",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/65.jpg",
        dateAdded: "2025-07-19"
    },
    {
        id: 66,
        title: "我的四个义姐妹",
        author: "えーり",
        translator: "兴趣使然的鸽子口牙",
        tags: ["古明地觉", "古明地恋", "芙兰朵露", "蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_5MZ8j-gDJYsVoMTrUsaYDk",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/7296370",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/66.jpg",
        dateAdded: "2025-11-18"
    },
    {
        id: 67,
        title: "想让认真的映姬害羞！！",
        author: "いなよりこりん",
        translator: "兴趣使然的鸽子口牙",
        tags: ["四季映姬"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL0y_WAo04qppy-nGEFpoU3jOCL7YcmPUk",
        translatedUrl: "https://www.bilibili.com/video/BV1suU1B9EtN",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/67.jpg",
        dateAdded: "2021-06-03"
    },
    {
        id: 68,
        title: "我的神明大人",
        author: "ゆっくりコスモス",
        translator: "兴趣使然的鸽子口牙",
        tags: ["洩矢诹访子", "魂魄妖梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLAhdzhAf7V75gG27SRl0pDGPlgbzcVICh",
        translatedUrl: "https://www.bilibili.com/video/BV1FjUpBDEhK",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/68.jpg",
        dateAdded: "2020-11-13"
    },
    {
        id: 69,
        title: "如果你死了却不传达心声，你会回到过去吗？！",
        author: "いなよりこりん",
        translator: "兴趣使然的鸽子口牙",
        tags: ["古明地恋", "芙兰朵露", "东风谷早苗"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL0y_WAo04qpqB__1sa_Lfg_fpDrJr713j",
        translatedUrl: "https://www.bilibili.com/video/BV1t7U9BnEXb",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/69.jpg",
        dateAdded: "2021-04-26"
    },
    {
        id: 70,
        title: "喜欢的人成了妹妹",
        author: "いなよりこりん",
        translator: "兴趣使然的鸽子口牙",
        tags: ["魂魄妖梦", "蕾米莉亚", "古明地觉"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL0y_WAo04qpoZV7cdhvAm1uvHwpWon7OM",
        translatedUrl: "https://www.bilibili.com/video/BV17MSnBGEMy",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/70.jpg",
        dateAdded: "2022-03-08"
    },
    {
        id: 71,
        title: "我的女友蕾米莉亚太过于傲娇！？",
        author: "えーり",
        translator: "兴趣使然的鸽子口牙",
        tags: ["蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=71RQTEyXIJM",
        translatedUrl: "https://www.bilibili.com/video/BV1ifrDBgEsk",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/71.jpg",
        dateAdded: "2024-09-20"
    },
    {
        id: 72,
        title: "讨厌男人的觉，只对我表现出爱意？！",
        author: "ツキミ草【ゆっくり】",
        translator: "孤独红人馆",
        tags: ["古明地觉", "博丽灵梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLuabzLomQRYWTM81MwVOowDWlPl35BQA3",
        translatedUrl: "https://space.bilibili.com/269144656/lists/5691537",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/72.jpg",
        dateAdded: "2024-12-30"
    },
    {
        id: 73,
        title: "捡到了被丢弃在纸箱里的少女",
        author: "みとは ゆっくり製作所",
        translator: "孤独红人馆",
        tags: ["多多良小伞", "古明地恋", "芙兰朵露", "古明地觉"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLVBIKA03FhZNMTGMmoiNvd2Z-0lndVwEu",
        translatedUrl: "https://space.bilibili.com/269144656/lists/6185918",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/73.jpg",
        dateAdded: "2025-05-12"
    },
    {
        id: 74,
        title: "东方深想录",
        author: "刹那 / Setsuna",
        translator: "孤独红人馆",
        tags: ["幻想入", "芙兰朵露", "蕾米莉亚", "博丽灵梦", "铃仙", "十六夜咲夜", "雾雨魔理沙", "爱丽丝", "射命丸文", "帕秋莉", "魂魄妖梦", "魂魄妖忌", "西行寺幽幽子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLbHQ_4GWYYBw_GstrSRD3iXeb2Xm8OALM",
        translatedUrl: "https://space.bilibili.com/269144656/lists/5792751",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/74.jpg",
        dateAdded: "2023-07-09"
    },
    {
        id: 75,
        title: "恋爱修罗场！？",
        author: "エレキワイズ",
        translator: "孤独红人馆",
        tags: ["射命丸文", "犬走椛", "神绮", "雾雨魔理沙", "爱丽丝", "宇佐见莲子", "姬海棠果"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLsGwA474Pdf4LA6ffmdi1GhrPmwpYFynZ",
        translatedUrl: "https://space.bilibili.com/269144656/lists/6726286",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/75.jpg",
        dateAdded: "2020-09-26"
    },
    {
        id: 76,
        title: "东方罪宝录",
        author: "ゆっくりダイヤ",
        translator: "孤独红人馆",
        tags: ["十六夜咲夜", "红美铃", "雾雨魔理沙", "蕾米莉亚", "芙兰朵露", "博丽灵梦", "八云紫"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLwR9AUMdH1nDqjotGxbAEisUuxkmdiEfr",
        translatedUrl: "https://space.bilibili.com/269144656/lists/6498268",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/76.jpg",
        dateAdded: "2023-03-25"
    },
    {
        id: 77,
        title: "孤独红人馆烤制的短篇合集",
        author: "孤独红人馆",
        translator: "孤独红人馆",
        tags: ["古明地恋", "古明地觉", "蕾米莉亚", "芙兰朵露", "铃仙", "八云紫", "小野塚小町", "爱丽丝", "雾雨魔理沙", "西行寺幽幽子", "魂魄妖梦", "铃仙", "辉夜", "藤原妹红", "博丽灵梦", "冴月麟", "比那名居天子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://space.bilibili.com/269144656/lists/6217334",
        translatedUrl: "https://space.bilibili.com/269144656/lists/6217334",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/77.jpg",
        dateAdded: "2025-08-01"
    },
    {
        id: 78,
        title: "早苗小姐变成病娇了？",
        author: "チワさん",
        translator: "律令之蓝间桐慎二",
        tags: ["东风谷早苗", "病娇", "古明地觉", "雾雨魔理沙", "蕾米莉亚", "小野塚小町", "古明地恋", "芙兰朵露", "十六夜咲夜"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL37r3qKBltuH0reW86oBsOVtlebXY5qTz",
        translatedUrl: "https://space.bilibili.com/276595758/lists/4759701",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/78.jpg",
        dateAdded: "2022-08-24"
    },
    {
        id: 79,
        title: "喝下奇怪药水变成病娇的恋酱",
        author: "ラカルとゆっくりB",
        translator: "律令之蓝间桐慎二",
        tags: ["古明地恋", "河城荷取"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLGFnsUX9c-tbjY1S8aogQ_wpKxx_k6MeF",
        translatedUrl: "https://space.bilibili.com/276595758/lists/4942139",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/79.jpg",
        dateAdded: "2020-07-17"
    },
    {
        id: 80,
        title: "食人妖怪露米娅与不会死的我",
        author: "まったりさん",
        translator: "律令之蓝间桐慎二",
        tags: ["露米娅", "蕾米莉亚", "芙兰朵露", "十六夜咲夜", "博丽灵梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=kMTCyHAIAAg",
        translatedUrl: "https://space.bilibili.com/276595758/lists/4922279",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/80.jpg",
        dateAdded: "2019-12-10"
    },
    {
        id: 81,
        title: "与同班同学心酱的同居生活！？",
        author: "ラカルとゆっくりB",
        translator: "律令之蓝间桐慎二",
        tags: ["秦心", "十六夜咲夜", "帕秋莉", "八云蓝", "八云紫"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLGFnsUX9c-taNHCTET0vw55T7Rg7Ahs49",
        translatedUrl: "https://space.bilibili.com/276595758/lists/5468957",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/81.jpg",
        dateAdded: "2020-05-06"
    },
    {
        id: 82,
        title: "恋咲刻",
        author: "まったりさん",
        translator: "永远的samsara",
        tags: ["蕾米莉亚", "古明地恋", "雾雨魔理沙"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPcclhR1wbagSiZEPY8vDI5K5I",
        translatedUrl: "https://space.bilibili.com/69111014/lists/6782814",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/82.jpg",
        dateAdded: "2018-08-03"
    },
    {
        id: 83,
        title: "拥有毁灭能力的少女",
        author: "きまぐれい『漫画部』",
        translator: "永远的samsara",
        tags: ["芙兰朵露", "古明地恋"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLwVn04n1IKXsCPUltmvPHDbZN27u0GF7c",
        translatedUrl: "https://space.bilibili.com/69111014/lists/6736921",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/83.jpg",
        dateAdded: "2022-10-13"
    },
    {
        id: 84,
        title: "全员都是妹妹！？《灵梦她们变成妹妹了…！？》",
        author: "まったりさん",
        translator: "永远的samsara",
        tags: ["博丽灵梦", "古明地恋", "魂魄妖梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL15bNp6jPcclhR1wbagSiZEPY8vDI5K5I",
        translatedUrl: "https://space.bilibili.com/69111014/lists/6759493",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/84.jpg",
        dateAdded: "2018-09-09"
    },
    {
        id: 85,
        title: "我的四个义姐妹也太可爱了吧",
        author: "えーり",
        translator: "永远的samsara",
        tags: ["古明地觉", "古明地恋", "蕾米莉亚", "芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_5MZ8j-gDJYsVoMTrUsaYDk",
        translatedUrl: "https://space.bilibili.com/69111014/lists/6780769",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/85.jpg",
        dateAdded: "2025-11-07"
    },
    {
        id: 86,
        title: "爱耍小聪明的学妹觉，其实超喜欢我！？",
        author: "えーり",
        translator: "永远的samsara",
        tags: ["古明地觉"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_6rQYUJdeW78ERQPC-0v6YK",
        translatedUrl: "https://space.bilibili.com/69111014/lists/6780758",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/86.jpg",
        dateAdded: "2024-12-27"
    },
    {
        id: 87,
        title: "被病娇的蕾米莉亚缠上了！？",
        author: "えーり",
        translator: "永远的samsara",
        tags: ["蕾米莉亚", "病娇"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_5mB4A0gda1yms9PZatnShM",
        translatedUrl: "https://space.bilibili.com/69111014/lists/6781571",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/87.jpg",
        dateAdded: "2025-05-11"
    },
    {
        id: 88,
        title: "恋恋好像变成猫了哟！？",
        author: "まったりさん",
        translator: "永远的samsara",
        tags: ["古明地恋"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL2X7X36J6V_5MZ8j-gDJYsVoMTrUsaYDk",
        translatedUrl: "https://space.bilibili.com/69111014/lists/6792287",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/88.jpg",
        dateAdded: "2019-07-04"
    },
    {
        id: 89,
        title: "班里人气超高的灵梦只对我展露本性",
        author: "ルウド",
        translator: "山上的幽灵_",
        tags: ["博丽灵梦", "魂魄妖梦", "洩矢诹访子"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=k_LE2xS6DO8",
        translatedUrl: "https://space.bilibili.com/3546752504302024/lists/6948568",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770358552/touhou/thumbnails/89.jpg",
        dateAdded: "2024-11-09"
    },
    {
        id: 90,
        title: "灵梦被魔理沙强行灌药变成男生",
        author: "白玉ぜんざいの人",
        translator: "山上的幽灵_",
        tags: ["博丽灵梦", "雾雨魔理沙", "魂魄妖梦", "十六夜咲夜", "东风谷早苗", "蕾米莉亚"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLrY1wPAyDmtPTUfWzUY_P8nIjdLYEEOwC",
        translatedUrl: "https://space.bilibili.com/3546752504302024/lists/6954186",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770358553/touhou/thumbnails/90.jpg",
        dateAdded: "2021-04-03"
    },
    {
        id: 91,
        title: "灵梦和魔理沙的甜蜜日常",
        author: "ゆっくりむむ",
        translator: "山上的幽灵_",
        tags: ["博丽灵梦", "雾雨魔理沙"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLHXOmf4JXBjvWHWnEijdrJMoW35Bx0rAH",
        translatedUrl: "https://space.bilibili.com/3546752504302024/lists/6989330",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770358554/touhou/thumbnails/91.jpg",
        dateAdded: "2025-10-07"
    },
    {
        id: 92,
        title: "我的周围好像只有病娇",
        author: "こよせ",
        translator: "山上的幽灵_",
        tags: ["病娇", "博丽灵梦", "芙兰朵露", "古明地恋", "雾雨魔理沙", "东风谷早苗", "魂魄妖梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=p3np4Czz2aI",
        translatedUrl: "https://space.bilibili.com/3546752504302024/lists/7321196",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770358555/touhou/thumbnails/92.jpg",
        dateAdded: "2025-12-19"
    },
    {
        id: 93,
        title: "前传-我的周围好像只有病娇",
        author: "こよせ",
        translator: "山上的幽灵_",
        tags: ["病娇", "东风谷早苗", "古明地恋", "博丽灵梦", "魂魄妖梦", "雾雨魔理沙"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=IciLDKyBWPg",
        translatedUrl: "https://space.bilibili.com/3546752504302024/lists/7330978",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770358555/touhou/thumbnails/93.jpg",
        dateAdded: "2025-09-10"
    },
    {
        id: 94,
        title: "爱丽丝成为妈妈了",
        author: "ゆっくりトポロジー",
        translator: "寄遗忘之物于流年",
        tags: ["爱丽丝"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLsfDuT-j_dJ4n48XIiNjlPkA-wRBCezP3",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7394791",
        description: "爱丽丝妈妈",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770978235/touhou/thumbnails/94.jpg",
        dateAdded: "2025-01-13"
    },
    {
        id: 95,
        title: "我与鬼的约定？！！",
        author: "快乐的小顺",
        translator: "",
        tags: ["伊吹萃香"],
        isTranslated: false,
        isDomestic: true,
        originalUrl: "https://space.bilibili.com/478979846/lists/5762210",
        translatedUrl: "",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770980258/touhou/thumbnails/95.webp",
        dateAdded: "2025-07-02"
    },
    {
        id: 96,
        title: "萃恋芙心",
        author: "快乐的小顺",
        translator: "",
        tags: ["伊吹萃香", "古明地恋", "芙兰朵露"],
        isTranslated: false,
        isDomestic: true,
        originalUrl: "https://space.bilibili.com/478979846/lists/6415865",
        translatedUrl: "",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770980258/touhou/thumbnails/96.webp",
        dateAdded: "2025-09-25"
    },
    {
        id: 97,
        title: "东方病娇",
        author: "某明Certainly",
        translator: "",
        tags: ["病娇", "纯狐", "霍青娥", "爱丽丝", "四季映姬", "芙兰朵露", "宫古芳香", "上白泽慧音", "辉夜", "键山雏"],
        isTranslated: false,
        isDomestic: true,
        originalUrl: "https://space.bilibili.com/80249082/lists/3720523",
        translatedUrl: "",
        description: "震撼来袭",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/touhou/thumbnails/97.jpg",
        dateAdded: "2024-08-26"
    },
    {
        id: 98,
        title: "关于我是早苗的青梅竹马一事",
        author: "虚空大灾难",
        translator: "",
        tags: ["东风谷早苗", "博丽灵梦"],
        isTranslated: false,
        isDomestic: true,
        originalUrl: "https://space.bilibili.com/20713352/lists/6631848",
        translatedUrl: "",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770980258/touhou/thumbnails/98.jpg",
        dateAdded: "2025-10-19"
    },
    {
        id: 99,
        title: "人鬼情未了",
        author: "古茗地華",
        translator: "",
        tags: ["伊吹萃香"],
        isTranslated: false,
        isDomestic: true,
        originalUrl: "https://www.bilibili.com/video/BV1cN89zyEDw",
        translatedUrl: "",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770980258/touhou/thumbnails/99.jpg",
        dateAdded: "2025-07-29"
    },
    {
        id: 100,
        title: "『幻想入的Jier』亲自操刀制作的茶番剧",
        author: "幻想入的Jier",
        translator: "",
        tags: ["琪露诺", "大妖精", "封兽鵺", "多多良小伞", "蕾米莉亚", "博丽灵梦", "雾雨魔理沙"],
        isTranslated: false,
        isDomestic: true,
        originalUrl: "https://space.bilibili.com/87123918/lists/5678896",
        translatedUrl: "",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770980258/touhou/thumbnails/100.jpg",
        dateAdded: "2025-06-17"
    },
    {
        id: 101,
        title: "如果东方的人物角色变成了病娇的话？",
        author: "チェイス【ゆっくり茶番劇】",
        translator: "楽園の魔法使",
        tags: ["病娇", "古明地觉", "十六夜咲夜", "古明地恋", "藤原妹红", "红美铃", "风见幽香", "露米娅", "圣白莲", "绵月丰姬", "丰聪耳神子", "魂魄妖梦", "比那名居天子", "蕾米莉亚", "博丽灵梦", "雾雨魔理沙", "铃仙", "犬走椛", "秦心", "帕秋莉", "芙兰朵露", "八云紫", "绵月依姬", "大妖精", "琪露诺"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/shorts/nNAkrSU1Ot8",
        translatedUrl: "https://space.bilibili.com/1650223739/lists/6055955",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/101.jpg",
        dateAdded: "2024-12-30"
    },
    {
        id: 102,
        title: "僕の恋と白色康乃馨",
        author: "〆タケ",
        translator: "幻想入的Jier",
        tags: ["多多良小伞", "露米娅"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=ySfxHPVSC88",
        translatedUrl: "https://www.bilibili.com/video/BV192dpYKEGM",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/102.jpg",
        dateAdded: "2023-09-03"
    },
    {
        id: 103,
        title: "原本期限一天的租借女友（芙兰）被我不小心租了一辈子？！",
        author: "〆タケ",
        translator: "幻想入的Jier",
        tags: ["芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLtbLg09TfEKpRAVdk1W7AmkquMHd5kr9P",
        translatedUrl: "https://www.bilibili.com/video/BV1aqCBY5Er7",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/103.jpg",
        dateAdded: "2023-04-08"
    },
    {
        id: 104,
        title: "相连的心",
        author: "〆タケ",
        translator: "幻想入的Jier",
        tags: ["秦心"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/watch?v=oTyt4zDiVUs",
        translatedUrl: "https://www.bilibili.com/video/BV1HoJXzQEw1",
        description: "——活下去",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/104.jpg",
        dateAdded: "2025-09-21"
    },
    {
        id: 105,
        title: "选错就重来，与键山雏的恋爱循环",
        author: "あーる。/ aru",
        translator: "就是很一般",
        tags: ["键山雏"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLkbhAsj-moQyfsoSE3orNw3tilwVfVEL7",
        translatedUrl: "https://www.bilibili.com/video/BV1uAunz5E3q",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/105.jpg",
        dateAdded: "2021-03-20"
    },
    {
        id: 106,
        title: "因惩罚游戏告白后竟和世界第一可爱的灵梦结婚了",
        author: "まったりさん",
        translator: "就是很一般",
        tags: ["博丽灵梦"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLSySOhc57uZY2zl7ffHvGfW6eIbWx1_Cb",
        translatedUrl: "https://www.bilibili.com/video/BV1kdVVzbEfY",
        description: "结婚系灵梦，梦里啥都有.jpg",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/106.jpg",
        dateAdded: "2023-04-30"
    },
    {
        id: 107,
        title: "『就是很一般』汉化的恋爱短篇",
        author: "就是很一般",
        translator: "就是很一般",
        tags: ["永江衣玖", "东风谷早苗", "古明地恋", "道神驯子", "洩矢诹访子", "爱丽丝", "十六夜咲夜", "依神紫苑", "宇佐见莲子", "芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://space.bilibili.com/12621850/lists/5264242",
        translatedUrl: "https://space.bilibili.com/12621850/lists/5264242",
        description: "油管上一些作者做的恋爱短篇茶番剧",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/107.jpg",
        dateAdded: "2025-03-08"
    },
    {
        id: 108,
        title: "小尬剧",
        author: "极悲",
        translator: "",
        tags: ["古明地觉", "古明地恋", "藤原妹红", "辉夜", "射命丸文", "犬走椛", "秦心", "魂魄妖梦", "西行寺幽幽子", "东风谷早苗", "纯狐", "多多良小伞", "绵月依姬", "露米娅", "埴安神袿姬"],
        isTranslated: false,
        isDomestic: true,
        originalUrl: "https://space.bilibili.com/3493276539685348/lists/5804379",
        translatedUrl: "",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/108.jpg",
        dateAdded: "2025-06-07"
    },
    {
        id: 109,
        title: "映姬所遗忘的妹妹们",
        author: "温柔的-露娜sama",
        translator: "",
        tags: ["四季映姬", "芙兰朵露", "博丽灵梦", "犬走椛", "魂魄妖梦", "古明地觉", "蕾米莉亚", "雾雨魔理沙", "稗田阿求"],
        isTranslated: false,
        isDomestic: true,
        originalUrl: "https://space.bilibili.com/521628660/lists/6025206",
        translatedUrl: "",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/109.jpg",
        dateAdded: "2025-07-04"
    },
    {
        id: 110,
        title: "盲目的少女与丑陋的少年",
        author: "ツキミ草【ゆっくり】",
        translator: "兴趣使然的鸽子口牙",
        tags: ["古明地恋", "东风谷早苗"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLuabzLomQRYUsFGKUThPnEMJ-zT2dxdBj",
        translatedUrl: "https://space.bilibili.com/3546748681194187/lists/7438204",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/110.jpg",
        dateAdded: "2025-05-07"
    },
    {
        id: 111,
        title: "一向高冷的王子殿下，唯独对我展露可爱一面\n·",
        author: "ゆっくりトポロジー",
        translator: "寄遗忘之物于流年",
        tags: ["藤原妹红"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLsfDuT-j_dJ7ZiG7V_a4828RPerwHFc7q",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7466744",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/111.jpg",
        dateAdded: "2025-05-30"
    },
    {
        id: 112,
        title: "史上最差最糟的狼人游戏",
        author: "夜桜チャンネル",
        translator: "黎仟憶_アリス",
        tags: ["博丽灵梦", "雾雨魔理沙", "八意永琳", "古明地恋", "古明地觉", "帕秋莉", "十六夜咲夜", "魂魄妖梦", "蕾米莉亚", "上白泽慧音", "八云紫", "芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL-1f8SJ_NruyUAAguD3t5Kxc0BwapRHaa",
        translatedUrl: "https://space.bilibili.com/1359356041/lists/4387144",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/112.jpg",
        dateAdded: "2023-07-11"
    },
    {
        id: 113,
        title: "被诅咒少女的幻想入",
        author: "夜桜チャンネル",
        translator: "黎仟憶_アリス",
        tags: ["幻想入", "八云紫", "雾雨魔理沙", "博丽灵梦", "蕾米莉亚", "芙兰朵露"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PL-1f8SJ_NruxsGgyZaefxrA96z8HxBERv",
        translatedUrl: "https://www.bilibili.com/video/BV1172tBqEjR",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/113.jpg",
        dateAdded: "2024-05-21"
    },
    {
        id: 114,
        title: "被入室小偷求婚的结果！？",
        author: "NOT教育系月蝕さんのゆっくり茶番劇Ch【不定期投稿中】",
        translator: "寄遗忘之物于流年",
        tags: ["多多良小伞"],
        isTranslated: true,
        isDomestic: false,
        originalUrl: "https://www.youtube.com/playlist?list=PLcVm5ie8VPeX4qRXt-TNzoGamNIPJjYYP",
        translatedUrl: "https://space.bilibili.com/109338384/lists/7466039",
        description: "",
        thumbnail: "https://res.cloudinary.com/do6rggmy6/image/upload/v1770352189/touhou/thumbnails/114.jpg",
        dateAdded: "2023-07-01"
    }
    {
  "id": 115,
  "title": "突然被美少女逼婚了 总集篇",
  "author": "あるふぁるふぁ",
  "translator": "寄遗忘之物于流年",
  "tags": [
    "多多良小伞",
    "古明地恋",
    "射命丸文",
    "上白泽慧音",
    "藤原妹红",
    "蕾米莉亚",
    "帕秋莉",
    "四季映姬",
    "本居小铃",
    "小野冢小町"
  ],
  "isTranslated": true,
  "isDomestic": true,
  "originalUrl": "https://www.youtube.com/watch?v=DTZSb_4gkPU",
  "translatedUrl": "https://www.bilibili.com/video/BV19VZPBGEgQ/",
  "description": "",
  "thumbnail": "",
  "dateAdded": "2026-02-16"
}
];

const authorLinks = {
    "OKOME": "https://www.youtube.com/@OKOME-j4z",
    "ささきの茶釜": "https://www.youtube.com/@%E3%81%95%E3%81%95%E3%81%8D%E3%81%AE%E8%8C%B6%E9%87%9C",
    "ラングリィ": "https://www.youtube.com/@LANGULY",
    "まったりさん": "https://www.youtube.com/@mattarisan",
    "DAIゆっくり": "https://www.youtube.com/@_dai6935",
    "白熱の親指": "https://www.youtube.com/@%E7%99%BD%E7%86%B1%E3%81%AE%E8%A6%AA%E6%8C%87-k6g",
    "須方のさんちゃん工房": "https://www.youtube.com/@%E9%A0%88%E6%96%B9%E3%81%AE%E3%81%95%E3%82%93%E3%81%A1%E3%82%83%E3%82%93%E5%B7%A5%E6%88%BF",
    "みつば【mituba】": "https://www.youtube.com/@mituba_clover",
    "ねんねまるゆっくり": "https://www.youtube.com/@nene-yukkuri",
    "不知火桃": "https://www.youtube.com/@shiranuimomo",
    "MISAKI 3518": "https://www.youtube.com/@MISAKI-3518",
    "みるもるの家": "https://www.youtube.com/@mirumoru",
    "Super_Nakachan": "https://www.youtube.com/@SuperNakachanTV",
    "転生さん": "https://www.youtube.com/@tensei_san",
    "月田瑞希": "https://www.youtube.com/@%E6%9C%88%E7%94%B0%E7%91%9E%E5%B8%8C",
    "東方キャラと恋愛するノベル動画ch": "https://www.youtube.com/@ch-vq5tf",
    "みとは ゆっくり製作所": "https://www.youtube.com/@rinne_mitoha",
    "〆タケ": "https://www.youtube.com/@Sime-Take",
    "ゆっくり紫月": "https://www.youtube.com/@%E3%82%86%E3%81%A3%E3%81%8F%E3%82%8A%E7%B4%AB%E6%9C%88",
    "森の民やむぅ": "https://www.youtube.com/@UTA413",
    "れくしぃちきん@ゆっくり茶番劇": "https://www.youtube.com/@req4chicken",
    "アスター": "https://www.youtube.com/@%E3%82%A2%E3%82%B9%E3%82%BF%E3%83%BC-q8x",
    "KOTATU": "https://www.youtube.com/@KOTATU3118",
    "一脚踢飞毛布": "https://space.bilibili.com/33819012",
    "就是很一般": "https://space.bilibili.com/12621850",
    "Baby_2016": "https://space.bilibili.com/499929312",
    "寄遗忘之物于流年": "https://space.bilibili.com/109338384",
    "幻想入的Jier": "https://space.bilibili.com/87123918",
    "ラカルとゆっくりB": "https://www.youtube.com/@Rakaru_to_yuukuriB",
    "シク−Siku−   ゆっくり": "https://www.youtube.com/@%E3%82%B7%E3%82%AF%E3%83%BCSiku%E3%83%BC%E3%82%86%E3%81%A3%E3%81%8F%E3%82%8A",
    "ゆっくりヴォルガ": "https://www.youtube.com/@yukkuriworuga",
    "ゆっくり春": "https://www.youtube.com/@HT-qp5vx",
    "幻夢 ゆっくり茶番劇": "https://www.youtube.com/@%E5%B9%BB%E5%A4%A2-q2c",
    "あーる。/ aru": "https://www.youtube.com/@aru1496",
    "ルナ「露優」": "https://www.youtube.com/@runa_tuyu",
    "じぇすさんのゆっくり部屋": "https://www.youtube.com/@jesusan203",
    "かめーーとあらら": "https://www.youtube.com/@kame--toarara",
    "ゆっくり「モナカ」": "https://www.youtube.com/@monaka-yukkuri",
    "東方紙芝居物語": "https://www.youtube.com/@TouhouYandere8901",
    "我都没眼看123": "https://space.bilibili.com/2065248047",
    "はやぶさ_ゆっくり茶番劇": "https://www.youtube.com/@HAYABUSAYukkuri",
    "兴趣使然的鸽子口牙": "https://space.bilibili.com/3546748681194187",
    "山上的幽灵_": "https://space.bilibili.com/3546752504302024",
    "孤独红人馆": "https://space.bilibili.com/269144656",
    "律令之蓝间桐慎二": "https://space.bilibili.com/276595758",
    "永远的samsara": "https://space.bilibili.com/69111014",
    "きまぐれい『漫画部』": "https://www.youtube.com/@Kimagu_REI",
    "いなよりこりん": "https://www.youtube.com/@korin.inayori",
    "アルカイ教": "https://www.youtube.com/@arukaikyou",
    "すみかぜハヤテ": "https://www.youtube.com/@SumIkazeHayate",
    "るちょ": "https://www.youtube.com/@%E3%82%8B%E3%81%A1%E3%82%87",
    "ゆっくりコスモス": "https://www.youtube.com/@%E3%82%86%E3%81%A3%E3%81%8F%E3%82%8A%E3%82%B3%E3%82%B9%E3%83%A2%E3%82%B9",
    "えーり": "https://www.youtube.com/@yukkuri_Eiri",
    "らうさん": "https://www.youtube.com/@rau3046",
    "ツキミ草【ゆっくり】": "https://www.youtube.com/@%E3%83%84%E3%82%AD%E3%83%9F%E8%8D%89",
    "刹那 / Setsuna": "https://www.youtube.com/@Setsuna-Setsuna",
    "エレキワイズ": "https://www.youtube.com/@erekiwaizu",
    "ゆっくりダイヤ": "https://www.youtube.com/@yukkuridaiya",
    "チワさん": "https://www.youtube.com/@Tiwasann",
    "ルウド": "https://www.youtube.com/@%E3%83%AB%E3%82%A6%E3%83%89",
    "白玉ぜんざいの人": "https://www.youtube.com/@shiratama-zenzai-",
    "ゆっくりむむ": "https://www.youtube.com/@mumumu0410",
    "こよせ": "https://www.youtube.com/@koyose_ch",
    "TheUsualHeartFade123": "https://space.bilibili.com/5838316",
    "ゆっくりトポロジー": "https://www.youtube.com/@yukkuri.topology",
    "快乐的小顺": "https://space.bilibili.com/478979846",
    "某明Certainly": "https://space.bilibili.com/80249082",
    "虚空大灾难": "https://space.bilibili.com/20713352/lists/6631848",
    "古茗地華": "https://space.bilibili.com/369600973",
    "チェイス【ゆっくり茶番劇】": "https://www.youtube.com/@CHASER126",
    "楽園の魔法使": "https://space.bilibili.com/1650223739",
    "极悲": "https://space.bilibili.com/3493276539685348",
    "温柔的-露娜sama": "https://space.bilibili.com/521628660",
    "降り注ぐ星の光": "https://space.bilibili.com/2041496991",
    "NOT教育系月蝕さんのゆっくり茶番劇Ch【不定期投稿中】": "https://www.youtube.com/@Ch-geltusyoku-%E8%8C%B6%E7%95%AA%E5%8A%87",
    "夜桜チャンネル": "https://www.youtube.com/@yozakura.ch7",
    "黎仟憶_アリス": "https://space.bilibili.com/1359356041"
    "寄遗忘之物于流年":"https://space.bilibili.com/109338384"
};
